#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx format:write --uncommitted
npx nx affected --target lint --uncommitted --fix true
npx nx affected --target test --uncommitted
npx nx affected --target e2e --uncommitted
